# Generated by Django 4.0.4 on 2022-05-31 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=400, verbose_name='Venue Address')),
                ('pincode', models.CharField(max_length=6, verbose_name='Venue Post Code')),
                ('web', models.URLField(blank=True, max_length=120, verbose_name='Venue Website')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('start_time', models.DateTimeField(default='2022-05-31 22:50')),
                ('end_time', models.DateTimeField(default='2022-05-31 23:50')),
                ('eventStatus', models.CharField(choices=[('Tn', 'Tentative'), ('Sc', 'Scheduled'), ('Cu', 'Coming Up This Week'), ('Ed', 'Event Day'), ('Cl', 'Closed'), ('Pv', 'Payments Verified')], default='Sc', max_length=20, verbose_name='Event Status')),
                ('Coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='public.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Name')),
                ('contact', models.CharField(max_length=10, null=True, verbose_name='Contact Number')),
                ('ageOfParticipants', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('13', 'Thirteen'), ('14', 'Fourteen'), ('15', 'Fifteen'), ('16', 'Sixteen')], default='1', max_length=20, verbose_name='Age')),
                ('paymentStatus', models.BooleanField(default=False, verbose_name='Aprroved')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.event')),
            ],
        ),
    ]
