# Generated by Django 4.0.4 on 2022-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='numOfParticipants',
        ),
        migrations.AddField(
            model_name='attendee',
            name='ageOfParticipants',
            field=models.CharField(max_length=2, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='contact',
            field=models.CharField(max_length=10, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
    ]
