# Generated by Django 4.0.4 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_attendee_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='ageOfParticipants',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('13', 'Thirteen'), ('14', 'Fourteen'), ('15', 'Fifteen'), ('16', 'Sixteen')], default='1', max_length=20, verbose_name='Age'),
        ),
    ]
