# Generated by Django 4.0.4 on 2022-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_attendee_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(choices=[('Tn', 'Tentative'), ('Sc', 'Scheduled'), ('Cu', 'Coming Up This Week'), ('Ed', 'Event Day'), ('Cl', 'Closed'), ('Pv', 'Payments Verified')], default='Sc', max_length=20, verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='2022-05-25 15:32'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='2022-05-25 14:32'),
        ),
    ]
